//
//  EssentialOilBlend.swift
//  Essential Oils Guide
//
//  Created by Adam Ure on 8/24/18.
//  Copyright © 2018 App Development with Swift. All rights reserved.
//

import Foundation

class oilBlend {
    var name: String
    var use: String
    var ingredients: [String]
    var warnings: String?
    
    init(name: String, use: String, ingredients: [String], warnings: String? = nil){
        self.name = name
        self.use = use
        self.ingredients = ingredients
        self.warnings = warnings
    }
    
    static func loadOriginalData() -> [oilBlend] {
        let oilBlends = [
            oilBlend(name: "Abundance", use: "This blend exemplifies the true power of synergy: Together, all of this component oils are magnified in vibration, creating the law of attraction and the energy and frequency of prosperity and plentitude.", ingredients: ["Orange", "Frankincense", "Patchouli", "Clove", "Ginger", "Myrrh", "Cinnamon Bark", "Spruce"]),
            oilBlend(name: "Acceptance", use: "Acceptance stimulates the mind, compelling us to open and accept new things, people, or relationships in life, allowing one to reach a higher potential. It also helps us to overcome procrastination and denial.", ingredients: ["Almond Oil", "Coriander", "Geranium", "Bergamot", "Frankincense", "Sandalwood", "Blue Tansy", "Neoli", "Ylang Ylang"]),
            oilBlend(name: "Aroma Life", use: "Aroma Life improves cardiovascular, lymphatic, and circulatory systems; lowers high blood pressure; and reduces stress.", ingredients: ["Sesame seed oil", "Cypress", "Marjoram", "Ylang Ylang", "Helichrysum"], warnings: nil),
            oilBlend(name: "Aroma Siez", use: "Aroma Siez is an advanced complex of anti-inflammatory, muscle-relaxing essential oils that promote circulation and relieve headaches and tight, inflamed, aching muscles resulting from injury, fatigue, or stress.", ingredients: ["Basil", "Marjoram", "Lavender", "Peppermint", "Cypress"], warnings: "Possible skin sensitivity."),
            oilBlend(name: "Australian Blue", use: "This blend includes a rare Australian aromatic called blue cypress, a part of the aboriginal pharmacopoeia for thousands of years. It is distilled from the wood of Callitris intratropica, the northern cypress pine, which has antiviral properties. Its aromatic influence uplifts and inspires whil simultaneously grounds and stabilzes.", ingredients: ["Blue Cypress", "Ylang Ylang", "Cedarwood", "Blue Tansy", "White Fir"], warnings: nil),
            oilBlend(name: "Awaken", use: "Five specific blends combine to awaken and enhance inner self-awareness that strengthens the desire to reach one's highest potential. It stimulates right brain creativity, amplifying the function of the pineal and pituitary glands in balancing the energy centers of the body and helps us identify our true desires and how best to pursue them.", ingredients: ["Fractionated (virgin) coconut oil", "Joy", "Forgiveness", "Present Time", "Dream Catcher", "Harmony"], warnings: "Possible sun sensitivity"),
            oilBlend(name: "Believe", use: "Believe helps release the unlimited potential everyone possesses. It restores feelings of hope, making it possible to more fully experience health, happiness, and vitality.", ingredients: ["Idaho Balsam Fir", "Coriander", "Bergamot", "Frankincense", "Idaho Blue Spruce", "Ylang Ylang", "Geranium"], warnings: "Possible skin sensitivity"),
            oilBlend(name: "Brian Power", use: "Brian Power promotes deep concentration and channels physical energy into mental energy. It also increases mental potential and clarity, and long-term use may retard the aging process. Many of the oils in this blend are high in sesquiterpene compounds that increase activity in the pineal, pituitary, and hypothalamus glands and thereby increase output of growth hormone and melatonin. The oils also help dissolve petrochemicals that congest the receptor sites, clearing the \"brain fog\" that people experience due to exposure to synthetic petrochemicals in food, skin, hair-care products, and air.", ingredients: ["Sandalwood", "Cedarwood", "Frankincense", "Melissa", "Blue Cypress", "Lavender", "Helichrysum"], warnings: "Possible skin sensitivity"),
            oilBlend(name: "Breate Again Roll-On", use: "This supercharged version of the R.C. blend is packaged in a convenient dispenser for easy use when air pollution makes it difficult to breathe or throat and nasal congestion strike. Contains four different eucalyptus oils and five additional essential oils, all known for their ability to relax airways, make breathing easier, and reduce coughing. In addition, these oils have anti-inflammatory characteristics.", ingredients: ["Fractionated (virgin) coconut oil", "Eucalyptus Staigeriana", "Eucalyptus Globulus", "Laurus Nobilis", "Rose hip seed oil", "Peppermint", "Eucalyptus Radiata", "Copaiba", "Myrtle", "Blue Cypress", "Eucalyptus Blue"], warnings: nil),
            oilBlend(name: "Chivalry", use: "Harkening back to stories of gallant knights of old, Chivalry instills respect, honor, and integrity. It empowers you to higher ideals and instills courage.", ingredients: ["Valor", "Ylang Ylang", "Joy", "Harmony", "Gratitude", "Rose", "Geranium"], warnings: "Possible sun/skin sensitivity."),
            oilBlend(name: "Christmas Spirit", use: "A purifying blend of evergreen, citrus, and spice, reminiscent of winter holidays, and brings joy, peace, happiness, and security.", ingredients: ["Orange", "Cinnamon Bark", "Spruce"], warnings: "Possible sun/skin sensitivity."),
            oilBlend(name: "Citrus Fresh", use: "Citrus Fresh stimulates the right brain to amplify creativity and well-being, eradicate anxiety, and works well as an air purifier. When diffused, it adds a clean, fresh scent to any environment.", ingredients: ["Orange", "Tangerine", "Grapefruit", "Lemon", "Mandarin", "Spearmint"], warnings: "Possible sun/skin sensitivity."),
            oilBlend(name: "Clarity", use: "Promotes a clear mind and amplifies mental alertness and vitality. It increases energy when overly tired and brings greeater focus to the spirit and mind.", ingredients: ["Basil", "Cardamom", "Rosemary", "Peppermint", "Coriander", "Geranium", "Bergamot", "Lemon", "Ylang Ylang", "Jasmine", "Roman Chamomile", "Palmarosa"], warnings: "Possible sun/skin sensitivity"),
            oilBlend(name: "Common Sense", use: "Common sense is a proprietary blend of pure Young Living essential oils especially formulated by D. Gary Young to increase mental acuity, helping to improve decision-making abilities and strengthen every-day thinking skills.", ingredients: ["Frankincense", "Ylang Ylang", "Ocotea", "Goldenrod", "Ruta", "Dorado Azul", "Lime"], warnings: nil),
            oilBlend(name: "Deep Relief Roll-On", use: "This convenient roll-on relieves muscle soreness and tension, soothes sore joints and ligaments, helps calm stressed nerves, and reduces inflammation. This powerful blend contains nine essential oils, most of which are known for their anti-inflammatory and pain-relieving characteristics. This highly portable roll-on with its no-mess application is easy to carry in your pocket, purse, brief case, etc. It also passes through airport security for \"easy breathing\" while flying high.", ingredients: ["Peppermint", "Fractioned (virgin) coconut oil", "Lemon", "Idaho Balsam Fir", "Clove", "Copaiba", "Wintergreen", "Helichrysum", "Vetiver", "Palo Santo"], warnings: "Keep out of reach of children. Do not ingest this blend. If pregnant, nursing, taking medication, or have a medical condition, consult a health-care professional prior to use."),
            oilBlend(name: "DiGize", use: "This blend relieves digestive problems, including indigestion, heartburn, gas, and bloating. It helps fight Candida as it kills and digests parasite infestation.", ingredients: ["Tarragon", "Ginger", "Peppermint", "Juniper", "Fennel", "Anise", "Patchouli", "Lemongrass"], warnings: "Possible sun sensitivity."),
            oilBlend(name: "Dragon Time", use: "This blend relieves PMS symptoms and menstrual discomforts, including cramping and irregular periods. It helps balance emotions, alleviating mood swings and headaches caused by hormonal imbalance.", ingredients: ["Fennel", "Clary sage", "Marjoram", "Lavender", "Yarrow", "Jasmine"], warnings: "Possible sun sensitivity."),
            oilBlend(name: "Dream Catcher", use: "This blend stimulates the emotional centers of the brain, awakening creative thoughts and enhancing dreams and visualizations, promoting greater potential for realizing your dreams and staying on your path. It also protects from negative thoughts and dreams that might cloud your vision.", ingredients: ["Sandalwood", "Tangerine", "Ylang Ylang", "Black Pepper", "Bergamot", "Juniper", "Anise", "Blue Tansy"], warnings: "Possible sun/skin sensitivity. Avoid direct sunlight or UV rays for 12 hours after applying product. If unpleasant dreams occur, continue to use, since subconscious memories and thoughts will stil need to be resolved. Hold on to your dreams and visualize the problems veing solved. It may be helpful to write the dreams down upon arising."),
            oilBlend(name: "Egyptian Gold", use: "This is a very unique blend that combines the most valuable essences of the Middle Easy and Central Europe. It offers a truly enchanting aromatic effect that stimulates the central nervous system and the immune and respiratory systems.", ingredients: ["Frankincense", "Lavender", "Idaho Balsam Fir", "Myrrh", "Spikenard", "Hyssop", "Cedarwood", "Rose", "Cinnamon Bark"], warnings: "Possible sun sensitivity."),
            oilBlend(name: "EndoFlex", use: "This blend amplifies metabolism and vitality and creates hormonal balance.", ingredients: ["Sesame seed oil", "Spearmint", "Sage", "Geranium", "Myrtle", "German Chamomile", "Nutmeg"], warnings: nil),
            oilBlend(name: "En-R-Gee", use: "This blend increases vitality, circulation, and alertness.", ingredients: ["Rosemary", "Juniper", "Lemongrass", "Nutmeg", "Idaho Balsam Fir", "Clove", "Black pepper"], warnings: "Possible skin sensitivity. Avoid contact with mucous membranes or sensitive skin. Not intended for use on children."),
            oilBlend(name: "Envision", use: "This blend renews focus and stimulates creative and intuitive abilities needed to achieve goals and dreams. It helps to reawaken internal drive and independence and to overcome fears and emotional blocks.", ingredients: ["Spruce", "Geranium", "Orange", "Lavender", "Sage", "Rose"], warnings: nil),
            oilBlend(name: "Evergreen Essence", use: "Evergreen Essence essential oil blend has a refreshing, crisp scent that is invigorating and emotionally strengthening. with an arrangement of popular evergreen trees, the scents of pine, fir, and spruce complement one another and may assist in the release of occasional emotional blocks. Refreshing to the sences, Evergreen Essence may bring a feeling of balance, peace, and security. The relaxing scent may also help clear the mind for a calming sense of meditation and reflection.", ingredients: ["Idaho Blue Spruce", "Idaho Ponderosa Pine", "Scotch Pine", "Red Fir", "Western Red Cedar", "White Fir", "Black Pine", "Pinyon Pine", "Lodgepole Pine"], warnings: nil),
            oilBlend(name: "Exodus II", use: "Some researchers believe that these aromatics were used by Aaron, the brother of Moses, to protect the Israelites from a plague. Modern science shows that these oils contain immune-stimulating and antimicrobial compounds. Because of the complex chemistry of essential oils, it is very difficult for viruses and bacteria to mutate and acquire resistance to them.", ingredients: ["Olive oil", "Myrrh", "Cassia", "Cinnamon Bark", "Calamus", "Hyssop", "Galbanum", "Spikenard", "Frankincense"], warnings: "Possible skin sensitivity. Not intended for children under 12 years of age, unless directed by a health professional."),
            oilBlend(name: "Forgiveness", use: "This blend helps to release hurt feelings and negative emotions. It also helps release negative memories, allowing one to move past emotional barriers and attain higher awareness, assisting the person to forgive and let go.", ingredients: ["Sesame seed oil", "Melissa", "Geranium", "Frankincense", "Sandalwood", "Coriander", "Angelica", "Lavender", "Bergamot", "Lemon", "Ylang Ylang", "Jasmine", "Helichrysum", "Roman Chamomile", "Palmarosa", "Rose"], warnings: "Possible sun/skin sensitivity. Avoid contact with eyes."),
            oilBlend(name: "Gathering", use: "This blend is created to help us overcome the bombardment of chaotic energy that alters our focus and takes us off our path toward higher achievements. Galbanum, a favorite oil of Moses, has a strong effect when blended with Frankincense and Sandalwood in gathering our emotional and spiritual thoughts, helping us to achieve our potential. These oils help increase the oxygen around the pineal and pituitary gland, bringing greater harmonic frequency to receive the communication we desire. This blend helps bring people together on a physical, emotional, and spiritual level for greater focus and clarity. It helps one stay focused, grounded, and clear in gathering one's potential for self-improvement.", ingredients: ["Lavender", "Geranium", "Galbanum", "Frankincense", "Sandalwood", "Ylang Ylang", "Spruce", "Cinnamon Bark", "Rose"], warnings: "Possible skin sensitivity."),
            oilBlend(name: "Gentle Baby", use: "This blend is comforting, soothing, relaxing, and beneficial for reducing stress during pregnancy. It helps reduce stretch marks and scar tissue, rejuvenates the skin, improves elasticity, and reduces wrinkles. It is particularly soothing to babies with dry, chapped skin and diaper rash. Skin issues improve when using Gentle Baby with Rose Ointment on the top of it. It is calming and brings a feeling of peace for tiny babies, children, and adults.", ingredients: ["Geranium", "Rosewood", "Coriander", "Palmarosa", "Lavender", "Ylang Ylang", "Roman Chamomile", "Lemon", "Jasmine", "Rose"], warnings: "Possible sun sensitivity."),
            oilBlend(name: "GLF", use: "The initials of this essential oil blend stand for Gallbladder and Liver Flush. It is formulated with oils that help to cleanse and restore liver and gallbladder function when taken in capsules as a dietary supplement.", ingredients: ["Ledum", "Helichrysum", "Celery Seed", "Grapefruit", "Hyssop", "Spearmint"], warnings: nil),
            oilBlend(name: "Gratitude", use: "This delightful blend is designed to elevate, soothe, and bring relief to the body while helping to foster a grateful attitude. It is also nourishing and supportive to the skin. The New Testament tells us that on one occasion, Christ healed 10 lepers (Luke 17:12-19), but only one returned to express his thanks. This blend embodies the spirit of that grateful leper.", ingredients: ["Idaho Balsam Fir", "Frankincense", "Coriander", "Myrrh", "Ylang Ylang", "Galbanum", "Bergamot", "Geranium"], warnings: "Possible skin sensitivity"),
            oilBlend(name: "Grounding", use: "This blend creates a feeling of solidarity and balance. It stabilizes and grounds us in order to cope constructively with reality. When we're hurting emotionally, we resort to avoidance. When this happens, it is easy to make poor choices that lead to unhealthy relationhsip and unwise business decisions. We seek to escape because we do not have anchoring or awareness to know how to deal with our emotions.", ingredients: ["White Fir", "Spruce", "Ylang Ylang", "Pine", "Cedarwood", "Angelica", "Juniper"], warnings: "Possible sun/skin sensitivity"),
            oilBlend(name: "Harmony", use: "This blend promotes physical and emotional healing by creating a harmonic balance for the energy centers of the body. It brings us into harmony with all things, people, and cycles of life. It is beneficial in reducing stress, amplifying well-being, and dissipating feelings of discord. It is also uplifting and elevating to the mind, creating a positive attitude.", ingredients: ["Sandalwood", "Lavender", "Ylang Ylang", "Frankincense", "Orange", "Angelica", "Geranium", "Hyssop", "Spanish Sage", "Spruce", "Coriander", "Bergamot", "Lemon", "Jasmine", "Roman Chamomile", "Palmarosa", "Rose"], warnings: "Possible sun/skin sensitivity"),
            oilBlend(name: "Highest Potential", use: "This blend combines powerful emotional blends with the most exotic essential oils of Jasmine and Ylang Ylang and the potent biblical oils of Frankincense, Galbanum, Cedarwood, and Sandalwood found in Gathering. It elevates the mind as you gather your thoughts and mental energy to achieve your highest potential. This blend harmonizes several grounding, calming, inspiring, and empowering essential oils into one intoxicating blend. Biochemist R. W. Moncrieff wrote that Ylang Ylang \"soothes and inhibits anger born of frustration,\" which removes road-blocks and opening new vistas. The uplifting fragrance of Jasmine spurs creativity, while the Lavender in Gathering clears the thought processes for focused intentions.", ingredients: ["Australian Blue", "Gathering", "Jasmine", "Ylang Ylang"], warnings: "Possible skin sensitivity."),
            oilBlend(name: "Hope", use: "Hope is essential for moving forward in life. Hopelessness can cause a loss of vision, goals, and dreams. This blend helps you to reconnect with a feeling of strength and grounding, restoring hope for tomorrow. It has helped many overcome suicidal depression.", ingredients: ["Almond Oil", "Melissa", "Juniper", "Myrrh", "Spruce"], warnings: "Possible skin sensitivity."),
            oilBlend(name: "Humility", use: "Having humility and forgiveness helps us to heal ourselves and our earth (Chronicles 7:14). Humility is an integral ingredient in obtaining forgiveness and is needed for a closer relationship with God. Through the frequency and fragrance of this blend, you may arrive at a place where healing can begin.", ingredients: ["Fractionated (virgin) coconut oil", "Coriander", "Ylang Ylang", "Bergamot", "Geranium", "Melissa", "Frankincense", "Myrrh", "Spikenard", "Neroli", "Rose"], warnings: nil),
            oilBlend(name: "ImmuPower", use: "This blend strengthens immunity and DNA repair in the cells. It is strongly antiseptic and anti-infectious.", ingredients: ["Hyssop", "Mountain Savory", "Cistus", "Ravintsara", "Frankincense", "Oregano", "Clove", "Cumin", "Idaho Tansy"], warnings: "Possible skin sensitivity. Test for sensitivity by putting a drop of oil on the underside of arm after diluting. These oils need to be well-diluted before using on children."),
            oilBlend(name: "Inner Child", use: "When children have been abused, they become disconnected from their inner child, or identity, which causes confusion. This fractures the personality and creates problems that tend to surface in the early- to mid-adult years, often mislabeled as a mid-life crisis. This fragrance stimulates memory response and helps one reconnect with the inner-self or identity. This is one of the first steps to finding emotional balance.", ingredients: ["Orange", "Tangerine", "Ylang Ylang", "Jasmine", "Sandalwood", "Lemongrass", "Spruce", "Neroli"], warnings: "Possible sun sensitivity."),
            oilBlend(name: "Inspiration", use: "This blend is formulated to help find a calm space in our minds and bring us closer to that creative center where our higher intuition operates. These oils were traditionally used by the Native Americans to enhance spirituality, prayer, and inner awareness.", ingredients: ["Cedarwood", "Spruce", "Myrtle", "Coriander", "Sandalwood", "Frankincense", "Bergamot", "Spikenard", "Vetiver", "Ylang Ylang", "Geranium"], warnings: "Possible skin sensitivity."),
            oilBlend(name: "Into the Future", use: "This blend helps one leave the past behind in order to progress with vision and excitement. So many times we find ourselves settling for mediocrity and sacrificing our own potential and success because of fear of the unknown and the future. This blend inspires determination and a pioneering spirit and creates a strong emotional feeling of being able to reach one's potential.", ingredients: ["Almond oil", "Clary sage", "Ylang Ylang", "White Fir", "Idaho Tansy", "Frankincense", "Jasmine", "Juniper", "Orange", "Cedarwood", "White Lotus"], warnings: "Possible sun/skin sensitivity"),
            oilBlend(name: "Joy", use: "This beautiful blend produces a magnetic energy that brings joy to the heart, mind, and soul. It inspires romance and helps overcome deep-seated grief and depression.", ingredients: ["Bergamot", "Ylang Ylang", "Geranium", "Lemon", "Coriander", "Tangerine", "Jasmine", "Roman Chamomile", "Palmarosa", "Rose"], warnings: nil),
            oilBlend(name: "JuvaCleanse", use: "The liver is the body's largest internal organ and major detoxifier. Even the toxins in the air we breathe are filtered by the liver, including chemicals from aerosol cleaners, paint, insect sprays, etc., but eventually those filters need to b e cleaned. The essential oils of Ledum, Celery Seed, and Helichrysum have long been known for their liver cleansing properties. JuvaCleanse was clinically tested in 2003 for removing mercury from body tissues. In 2003 a study conducted by Roger Lewis, MD, at the Young Life Research Clinic in Springville, Utah, evaluated the efficacy of Helichrysum, Ledum, and Celery Seed in treating cases of advanced Hepatitis C. In one case a 20-year-old male diagnosed with Hepatitis C had a viral count of 13,200. After taking two capsules (approx. 750 mg each) of JuvaCleanse per day for one month with no other intervention, the patient's viral count dropped more than 80 percent to 2,580.", ingredients: ["Helichrysum", "Celery Seed", "Ledum"], warnings: nil),
            oilBlend(name: "JuvaFlex", use: "This blend helps with liver and lymphatic detoxification. The emotions of anger and hate create toxins that are stored in the liver that can lead to sickness and disease. JuvaFlex helps break addictions to coffee, alcohol, drugs, and tobacco.", ingredients: ["Sesame seed oil", "Fennel", "Geranium", "Rosemary", "Roman Chamomile", "Blue tansy", "Helichrysum"], warnings: nil),
            oilBlend(name: "Lady Sclareol", use: "This oil, rich in phytoestrogens, is designed to be worn with its exquisite fragrance. It enhances the feminine nature by improving mood and raising estrogen levels. It may also provide relief for PMS symptoms.", ingredients: ["Coriander", "Geranium", "Vetiver", "Orange", "Clary Sage", "Bergamot", "Ylang Ylang", "Sandalwood", "Spanish Sage", "Jasmine", "Idaho Tansy"], warnings: nil),
            oilBlend(name: "Live with Passion", use: "This blend revives the zest for life and improves internal energy with a combination of essential oils formulated specifically to help people attain an optimistic attitude.", ingredients: ["Sandalwood", "Clary Sage", "Ginger", "Jasmine", "Patchouli", "Cedarwood", "Helichrysum", "Angelica", "Melissa", "Neroli"], warnings: nil),
            oilBlend(name: "Longevity", use: "This oil contains the highest antioxidant and DNA-protecting essential oils. When taken as a dietary supplement, this blend promotes longevity and prevents premature aging.", ingredients: ["Thyme", "Orange", "Clove", "Frankincense"], warnings: nil),
            oilBlend(name: "M-Grain", use: "This blend helps relieve pain from slight headaches to severe migraine headaches. It is anti-inflammatory and antispasmodic.", ingredients: ["Basil", "Marjoram", "Lavender", "Roman Chamomile", "Peppermint", "Helichrysum"], warnings: "Possible skin sensitivity."),
            oilBlend(name: "Magnify Your Purpose", use: "This blend stimulates the endocrine system for greater energy flow to the right hemisphere of the brain, activating creativity, motivation, and focus. This helps strengthen commitment to purpose, desire, and intentions until you realize your goals.", ingredients: ["Sandalwood", "Sage", "Coriander", "Patchouli", "Nutmeg", "Bergamot", "Cinnamon Bark", "Ginger", "Ylang Ylang", "Geranium"], warnings: "Possible skin sensitivity."),
            oilBlend(name: "Melrose", use: "This is a blend of four essential oils that have strong antiseptic properties to cleanse and disinfect cuts, scrapes, burns, rashes, and bruised tissue. These oils help regenerate damaged tissue and reduce inflammation. It is powerful when diffused to dispel odors, purify the air, and protect against daily radiation bombardment.", ingredients: ["Rosemary", "Melaleuca", "Clove", "Niaouli"], warnings: "Possible skin sensitivity."),
            oilBlend(name: "Mister", use: "This blend helps to decongest the prostate and promote greater male hormonal balance.", ingredients: ["Sesame seed oil", "Sage", "Fennel", "Lavender", "Myrtle", "Yarrow", "Peppermint"], warnings: nil),
            oilBlend(name: "Motivation", use: "Motivation stimulates feelings of action and accomplishment, providing positive energy to help overcome feelings of fear and procrastination.", ingredients: ["Roman Chamomile", "Spruce", "Ylang Ylang", "Lavender"], warnings: nil),
            oilBlend(name: "Oola Balance", use: "Young Living and Oola have partnered together to offer this one-of-a-kind essential oil blend, Oola Balance. This blend is designed to align and balance your center, giving you an increase in concentration with a positive outlook. As mind and body are balanced, the ability to focus on passions, behaviors, and health are amplified for the better.", ingredients: ["Lavender", "Frankincense", "Ylang Ylang", "Sacred Frankincense", "Idaho Balsam Fir", "Jasmine", "Sandalwood", "Galbanum", "Orange", "Angelica", "Geranium", "Myrrh", "Hyssop", "Ocotea", "Spanish Sage", "Spruce", "Cistus", "Spikenard", "Coriander", "Bergamot", "Lemon", "Roman Chamomile", "Palmarosa", "Rose"], warnings: nil),
            oilBlend(name: "Oola Grow", use: "Young Living and Oola have partnered together to offer this one-of-a-kind essential oil blend, Oola Grow. This blend is designed to help you reach unlimited potential and growth in many aspects of life. Whether it's emotional, spiritual, or mental, Oola Grow gives you courage to focus on the task at hand and helps you move forward toward positive advancements and progression.", ingredients: ["Fractionated (virgin) coconut oil", "Sweet almond oil", "Roman Chamomile", "Spruce", "Blue Cypress", "Coriander", "Clary Sage", "Ylang Ylang", "Geranium", "Bergamot", "Jasmine", "Rosewood", "Cedarwood", "White Fir", "Lavender", "Frankincense", "Galbanum", "Juniper", "Orange", "Sandalwood", "Blue Tansy", "Idaho Tansy", "Neroli", "Cinnamon Bark", "Rose", "White Lotus"], warnings: nil),
            oilBlend(name: "PanAway", use: "This very popular blend reduces pain and inflammation, increases circulation, and accelerates healing. It relieves swelling and discomfort from arthritis, sprains, muscle spasms, cramps, bumps, and bruises.", ingredients: ["Wintergreen", "Helichrysum", "Clove", "Peppermint"], warnings: "Possible skin sensitivity."),
            oilBlend(name: "Peace & Calming", use: "This blend promotes relaxation and a deep sense of peace and emotional well-being, helping to dampen tensions and uplift spirits. When massaged on the bottoms of feet, it can be a wonderful prelude to a peaceful night's rest. It may calm overactive and hard-to-manage children. It also reduces depression, anxiety, stress, and insomnia.", ingredients: ["Tangerine", "Orange", "Ylang Ylang", "Patchouli", "Blue Tansy"], warnings: "Possible sun/skin sensitivity."),
            oilBlend(name: "Present Time", use: "This blend is an empowering fragrance that creates a feeling of being in the moment. Disease develops when we live in the past and with regret. Being in the present time is the key to progressing and moving forward.", ingredients: ["Almond oil", "Neroli", "Spruce", "Ylang Ylang"], warnings: nil),
            oilBlend(name: "Purification", use: "This purifying blend cleanses and disinfects the air and neutralizes mildew, cigarette smoke, and disagreeable odors. It disinfects and cleans cuts, scrapes, and bites from spiders, bees, hornets, and wasps.", ingredients: ["Citronella", "Lemongrass", "Rosemary", "Melaleuca Alternifolia", "Lavandin", "Myrtle"], warnings: "Possible skin sensitivity"),
            oilBlend(name: "Raven", use: "The oils of this blend fight against respiratory disease and infections such as tuberculosis, influenza, and pneumonia. It is highly antiviral and antiseptic", ingredients: ["Ravintsara", "Lemon", "Wintergreen", "Peppermint", "Eucalyptus Radiata"], warnings: "Possible sun/skin sensitivity"),
            oilBlend(name: "R.C.", use: "R.C. gives relief from colds, bronchitis, sore throats, sinusitis, coughs, and respiratory congestion. It decongests sinus passages, combats lung infections, and relieves allergy symptoms.", ingredients: ["Myrtle", "Eucalyptus Globulus", "Marjoram", "Pine", "Eucalyptus Citriodora", "Lavender", "Cypress", "Eucalyptus Radiata", "Spruce", "Peppermint"], warnings: "Possible skin sensitivity."),
            oilBlend(name: "Release", use: "This is a helpful blend to release anger and memory traouma from the liver in order to create emotional well-being. It helps open the subconscious mind through pineal stimulation to release deep-seated trauma. It is one of the most pwerful of the emotionally supporting essential oil blends.", ingredients: ["Ylang Ylang", "Olive oil", "Lavindin", "Geranium", "Sandalwood", "Blue Tansy"], warnings: nil),
            oilBlend(name: "Relieve It", use: "This blend is high in anti-inflammatory compounds that relieve deep tissue pain and muscle soreness.", ingredients: ["Spruce", "Black Pepper", "Hyssop", "Peppermint"], warnings: "Possible skin sensitivity."),
            oilBlend(name: "RutaVaLa", use: "RutaVaLa is a proprietary blend of Ruta graveolens (Ruta), Lavender, and Valerian essential oils that promotes relaxation of the body and mind, soothes stressed nerves, and induces sleep. Ruta has long been used in South America to promote the relaxation of body and mind, relieve and soothe stressed nerves, and revitalize passion.", ingredients: ["Lavender", "Valerian", "Ruta"], warnings: nil),
            oilBlend(name: "RutaVaLa Roll-On", use: "RutaVaLa Roll-On is a proprietary blend of Ruta graveolens (Ruta), Lavender, and Valerian essential oils that promotes relaxation of the body and mind, soothes stressed nerves, and induces sleep. Ruta has long been used in South America to promote the relaxation of body and mind, relieve and sooth stressed nerves, and revitalize passion.", ingredients: ["Fractionated (virgin) coconut oil", "Lavender", "Valerian", "Ruta"], warnings: "Possible skin/sun sensitivity. If you are pregnant or have a medical condition, consult with a health professional prior to use. Do a skin test before using by putting one drop on the sensitive skin area under the arm. Keep away from eyes and mucus membranes."),
            oilBlend(name: "Sacred Mountain", use: "Mountain aromas instill strength, empowerment, grounding, and protection with the spiritual feeling of being in a sacred environment.", ingredients: ["Spruce", "Ylang Ylang", "Idaho Balsam Fir", "Cedarwood"], warnings: "Possible skin sensitivity."),
            oilBlend(name: "SARA", use: "This very specific blend enables one to relax into a mental state to facilitate the release of trauma from sexual and/or ritual abuse. SARA also helps unlock other traumatic experiences such as physical and emotional abuse.", ingredients: ["Almond oil", "Ylang Ylang", "Geranium", "Lavender", "Orange", "Blue Tansy", "Cedarwood", "White Lotus", "Rose"], warnings: "Possible sun sensitivity."),
            oilBlend(name: "SclarEssence", use: "This blend balances hormones naturally using essential oil phytoestrogens. It helps to increase estrogen levels by supporting the body's own production of hormones. It combines the soothing effects of Peppermint with the balancing power of Fennel and Clary Sage and the calming action of Spanish Sage for an extraordinary dietary supplement.", ingredients: ["Clary Sage", "Spanish Sage", "Peppermint", "Fennel"], warnings: "Do not use in conjunction with any other hormone products."),
            oilBlend(name: "Sensation", use: "This beautiful smell is profoundly romantic, refreshing, and arousing. It amplifies the excitement of experiencing new heights of self-expression and awareness. Sensation is also nourishing and hydrating for the skin and is beneficial for many skin problems.", ingredients: ["Coriander", "Ylang Ylang", "Bergamot", "Jasmine", "Geranium"], warnings: "Possible skin sensitivity."),
            oilBlend(name: "Slique Essence", use: "Slique Essence combines powerful essential oils and stevia estract to support healthy weight-management goals. It suppresses food cravings, especially when used in conjunction with Slique Tea or any of the Slique products. The oils in this blend add a flavorful and uplifting element to any day, with the added support of Spearmint to aid proper digestion. Ocotea essential oil was chosen for its irresistible cinnamon-esque aroma, which can help trigger feelings of fullness and reduce the number of unexpected cravings. Slique Essence is antibacterial, antifungal, a lipid regulator, and a glucose regulator. Stevia is added as an all-natural sweetener that provides a pleasant, sweet taste with no added calories.", ingredients: ["Grapefruit", "Tangerine", "Spearmint", "Lemon", "Ocotea", "Stevia"], warnings: "The Stevia extract in this formula may impede diffuser performance."),
            oilBlend(name: "Stress Away", use: "This is a gentle, fragrant blend that brings a feeling of peace and tranquility to both children and adults and helps to relieve daily stress and nervous tension. It helps with normal, everyday stress, improves mental response, retores equilibrium, promotes relaxation, and lower hypertension.", ingredients: ["Copaiba", "Lime", "Cedarwood", "Vanilla", "Ocotea", "Lavender"], warnings: nil),
            oilBlend(name: "Surrender", use: "This inviting oil helps one surrender aggression and a controlling attitude. Stress and tension are released quickly when we surrender willfulness.", ingredients: ["Lavender", "Lemon", "Roman Chamomile", "Spruce", "Angelica", "German Chamomile", "Mountain Savory"], warnings: "Possible sun/skin sensitivity."),
            oilBlend(name: "The Gift", use: "The Gift is the very \"essence of Arabia,\" blending the oils of antiquity into a most unique and exotic fragrance. It combines seven ancient therapeutic oils to capture the spirit of Arabia. This oil blend represents Mary's gift to Gary in honor of Shutran's noble journey through the book The One Gift, a historical novel depicting the wit, intrigue, sorrow, and romance of the ancient frankincense and myrrh caravans. Out of the writings and legends of antiquity, they mysteries unfold as we discover their powerful uses for healing the injuries of war, accidents, scorpion stings, and snakebites and in sacred rituals for attaining greater spiritual attunement for healing and protecting the body. Present-day science is now documenting the properties of these oils that augment the immune system, stimulate healing, and overcome depression. Myrrh and Frankincense are being touted for their anticancer, anti-infectious, antibacterial and antiviral abilities, as well as being a topical anesthesia and having the ability to regenerate bone and cartilage. they are the oldest known substances for their immune stimulating and healing powers to ever come out of the ancient world.", ingredients: ["Sacred Fankincense", "Idaho Balsam Fir", "Jasmine", "Galbanum", "Myrrh", "Cistus", "Spikenard"], warnings: nil),
            oilBlend(name: "Thieves", use: "This is a most amazing blend of highly anti-viral, antiseptic, antibacterial, and anti-infectious essential oils. It was created from research based on legends about a group of 15th-century thieves who rubbed oils on themselves to avoid contracting the plague while they robbed the bodies of the dead and dying. When apprehended, the thieves were forced to tell what their secret was an disclosed the formula of the herbs, spices, and oils they used to protect themselves in exchange for more lenient punishment. Studies conducted at Weber State University (Ogden, UT) during 1997 demonstrated the killing power of these amazing oils against airborne microorganisms. The analysis showed that after 10 minutes of Thieves diffusion in the air, there was an 82% reduction in the gram positive Micrococcus luteus organism bioaerosol, a 96% reduction in gram negative Pseudomonas aeruginosa organism bioaerosol, and a 44% reduction in S. aureus bioaerosol (Chao SC, et al., 1998).", ingredients: ["Clove", "Lemon", "Cinnamon Bark", "Eucalyptus Radiata", "Rosemary"], warnings: "Possible sun/skin sensitivity"),
            oilBlend(name: "Three Wise Men", use: "This b lend of 3 Wise Men promotes feelings of reverence and spiritual awareness combined with the power of therapeutic-grade essential oils that open the subconscious. It is considered a gift by many and enhances emotional equilibrium as it soothes and uplifts the heart.", ingredients: ["Almond oil", "Sandalwood", "Juniper", "Frankincense", "Spruce", "Myrrh"], warnings: nil),
            oilBlend(name: "Tranquil Roll-On", use: "This proprietary blend of Lavender, cedarwood, and Roman Chamomile essential oils, packaged in a roll-on applicator, provides convenient and portable relaxation and stress relief. All three of these oils have been well documented as being effective in reducing restlessness, decreasing anxiety, and inducing a calming feeling to mind and body. Their combined effect is uplifting as well as relaxing and can be useful in promoting sleep as well as reducing stress.", ingredients: ["Lavender", "Cedarwood", "Fractioned (virgin) coconut oil", "Roman Chamomile"], warnings: nil),
            oilBlend(name: "Transformation", use: "Repressed trauma and tragedy from the past may be out of sight, but they are definitely not out of mind. Memories are imprinted in our cells for better or worse. Stored negative emotions need to be replaced with joy, hope, courage. Transformation blend radiates with the purifying oils of Lemon and Peppermint, along with the revitalizing power of sesquiterpenes from Sandalwood and Frankincense. Idaho Blue Spruce anchors new mental programming. Reaching into the deepest recesses of memory, Transformation empowers and upholds the changes you want to make in your belief system. Positive, uplifting beliefs are foundational for the transformation of behavior.", ingredients: ["Lemon", "Peppermint", "Clary Sage", "Sandalwood", "Idaho Blue Spruce", "Sacred Frankincense", "Cardamom", "Palo Santo", "Ocotea"], warnings: nil),
            oilBlend(name: "Trauma Life", use: "The emotional trauma from accidents, death of loved ones, assault, abuse, etc., can implant its devastation deep within the hidden recesses of the mind, causing life-long problems that seem endless. Being able to release such burdens can bring about a new \"lease on life\" with a return to motivation and vitality. This blend combats stress and uproots trauma that cause insomnia, anger, restlessness, and a weakened immune response.", ingredients: ["Sandalwood", "Frankincense", "Valerian", "Spruce", "Davana", "Lavender", "Geranium", "Helichrysum", "Citrus Hystrix", "Rose"], warnings: "Possible sun/skin sensitivity."),
            oilBlend(name: "Valor", use: "This blend was formulated to balance energies and instill courage, confidence, and self-esteem. It helps the body self-correct its balance and alignment.", ingredients: ["Fractionated (virgin) coconut oil", "Spruce", "Rosewood", "Blue Tansy", "Frankincense"], warnings: nil),
            oilBlend(name: "Valor Roll-On", use: "Valor Essential Oil Roll-On is an empowering combination of therapeutic-grade essential oils that works with both the physical and spiritual aspects of the body to increase feelings of strength, courage, and self-esteem in the face of adversity. Renowned for its strengthening qualities, Valor enhances an individual's internal resources. It has also been found to help energy alignment in the body. This has become a very popular blend, now offered in a portable, convenient, roll-on application.", ingredients: ["Fractionated (virgin) coconut oil", "Spruce", "Rosewood", "Frankincense", "Blue Tansy"], warnings: nil),
            oilBlend(name: "White Angelica", use: "Increases and strengthens the aura around the body to bring a renewed sense of strength and protection, creating a feeling of wholeness in the realm of one's own spirituality. Its frequency neutralizes negative energy and gives a feeling of security.", ingredients: ["Fractionated (virgin) coconut oil", "Myrrh", "Bergamot", "Sandalwood", "Geranium", "Ylang Ylang", "Spruce", "Rosewood", "Coriander", "Hyssop", "Melissa", "Rose", "Angelica"], warnings: nil)
        ]
        return oilBlends
    }
}
